dist: xenial
language: node_js
node_js:
  - 'lts/*'
  - 'node'

before_install:
  - 'pyenv global 3.6'
  - 'pip install pip --upgrade'

install:
  - bash build/travis_install

script:
  - make

after_script:
  - npm run coverage:codecov
