dist: xenial
language: node_js
node_js:
  - 'lts/*'
  - 'node'

before_install:
  - sudo apt-get update
  - sudo apt-get install python3.8-minimal

install:
  - bash build/travis_install

script:
  - make

after_script:
  - npm run coverage:codecov
